version: "3"

services:
  neo4j:
    image: "neo4j:4.4.9"
    container_name: neo4j-metabolike
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      # TODO these actually work?
      - neo4j-data:/data
      - neo4j-logs:/logs
      # TODO define this if i care
      - "./plugins:/plugins" # 
    environment: # 
      # TODO need to comment these / actually download APOC full and put in plugins?
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=false
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes # 
    env_file:
      # TODO what is this?
      - .env # 

volumes:
  # TODO need to specify paths here?
  neo4j-data:
  neo4j-logs:

